- hosts: '{{ host }}'
  tasks:
    - name: create workdir
      file:
        path: '{{ playbook_dest }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: create destroy script
      template:
        dest: '{{ playbook_dest }}/destroy.sh'
        src: 'templates/destroy.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: create clean script
      template:
        dest: '{{ playbook_dest }}/clean.sh'
        src: 'templates/clean.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: stop and remove existing container
      command: "{{ playbook_dest }}/destroy.sh"
      ignore_errors: true
      tags: [ 'deploy' ]

    - name: clean docker images and containers
      command: "{{ playbook_dest }}/clean.sh"
      ignore_errors: true
      tags: [ 'deploy' ]

